### ISSUE TITLE
Using RxGcm without handling Foreground

### ISSUE THREAD

**Issue by ReginFell** [VictorAlbertos/RxGcm#7] opened 2016-04-20 05:58 UTC
Hi! 
Is there any way to implement only background notification even if application on foreground right now? 
Something kinda 
`RxGcm.Notifications.register(Application.getApplication(), null, GcmReceiverBackground.class)`

**Comment by NeoLSN** [comment] 2016-04-20 07:45
I also have the same requirement.
And there are also some findings.

1) Right now, library will crash if you are on the page which didn't implement `GcmReceiverUIForeground`.

2) Even you do implement `GcmReceiverUIForeground` but let `target()` return null, it still crashed the library.

**Comment by VictorAlbertos** [comment] 2016-04-21 07:33
Hi @ReginFell :)

That’s not possible. The library forces you to set this approach because it was designed with that architectural purpose. 

In order to be able to receive notifications on background, you need to implement first `GcmReceiverData` interface. That’s because `GcmReceiverData` is the first element to be notified -and where you should update your data models by the way, and after that, and ONLY after that,  `GcmReceiverUIBackground` or  `GcmReceiverUIForeground` implementations will be notified -depending on if app is on background or foreground state. If you don’t supply a `GcmReceiverData` no one after that will be notified. And, again, the library forces you to set this approach because it was designed with that architectural purpose. :)

**Comment by VictorAlbertos** [comment] 2016-04-21 07:41
Hi @NeoLSN

About the first issue, could you supply an example in order to illustrate the problem. Because I don't think that's possible, but maybe I'm wrong :)

And about the second one, yes, that's true, you need to return an empty string instead of a null value, as you can see in the [internal implementation](https://github.com/VictorAlbertos/RxGcm/blob/master/rx_gcm/src/main/java/rx_gcm/internal/GetGcmReceiversUIForeground.java#L57) there is no check against null values. I'm opening an issue to address this problem. Thanks ;)

**Comment by VictorAlbertos** [comment] 2016-04-21 08:16
@NeoLSN you were right. If the current fragment/activity did not implement `GcmReceiverUIForeground` the app would crash due -again- to a not checking null value. 

Both issues has been fixed in the last [0.2.2 release](https://github.com/VictorAlbertos/RxGcm/releases/tag/0.2.2)

Thanks for your feedback. And by the way, I'm closing the issue right now, but feel free to reopen whenever you need.

**Closed as completed by VictorAlbertos** 2016-04-21 08:16 UTC

**Comment by NeoLSN** [comment] 2016-04-21 08:20
Hi @VictorAlbertos 

I didn't implement any `GcmReceiverUIForeground` in my project.
My app will be crashed when it is opening because my activity or fragment didn't have `void onMismatchTargetNotification(Observable<Message> oMessage);` method in my project.

And sorry for not giving a example to you.

**Comment by VictorAlbertos** [comment] 2016-04-21 08:25
@NeoLSN, can you please try the new release and let me know if the problem persists?

Thanks!

**Comment by NeoLSN** [comment] 2016-04-21 08:41
@VictorAlbertos 

It is worked. Thanks!
